name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-build:
    name: test build
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run tests
      run: go test
